"""empty message

Revision ID: 3fc075b4a971
Revises: 
Create Date: 2022-05-01 23:58:26.838346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc075b4a971'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('edad', sa.Float(), nullable=False),
    sa.Column('favorito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorito_id'], ['favoritos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('clima', sa.String(length=20), nullable=False),
    sa.Column('terreno', sa.String(length=20), nullable=False),
    sa.Column('poblacion', sa.Float(), nullable=False),
    sa.Column('favorito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorito_id'], ['favoritos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planetas')
    op.drop_table('personajes')
    op.drop_table('favoritos')
    op.drop_table('user')
    # ### end Alembic commands ###
