"""empty message

Revision ID: 9a129135e1f5
Revises: 3fc075b4a971
Create Date: 2022-05-02 00:04:29.382829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a129135e1f5'
down_revision = '3fc075b4a971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoritos', sa.Column('personaje_id', sa.Integer(), nullable=True))
    op.add_column('favoritos', sa.Column('planeta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favoritos', 'personajes', ['personaje_id'], ['id'])
    op.create_foreign_key(None, 'favoritos', 'planetas', ['planeta_id'], ['id'])
    op.drop_constraint('personajes_ibfk_1', 'personajes', type_='foreignkey')
    op.drop_column('personajes', 'favorito_id')
    op.drop_constraint('planetas_ibfk_1', 'planetas', type_='foreignkey')
    op.drop_column('planetas', 'favorito_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planetas', sa.Column('favorito_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planetas_ibfk_1', 'planetas', 'favoritos', ['favorito_id'], ['id'])
    op.add_column('personajes', sa.Column('favorito_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('personajes_ibfk_1', 'personajes', 'favoritos', ['favorito_id'], ['id'])
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.drop_column('favoritos', 'planeta_id')
    op.drop_column('favoritos', 'personaje_id')
    # ### end Alembic commands ###
