"""empty message

Revision ID: e00f10010998
Revises: 7a588d79d5e6
Create Date: 2022-05-04 03:39:16.313544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00f10010998'
down_revision = '7a588d79d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('dont_repeat_favorites', 'favorites', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dont_repeat_favorites', 'favorites', type_='unique')
    # ### end Alembic commands ###
